name: $(Date:yyyy.MM.dd)-ado-init-agents-$(Build.BuildId)
trigger: none

#pool: new-IDA-agentpool
# pool: automation-agents
pool: Azure pipelines

variables:
- group: agent_details
# - group: NGC-ACR

stages:
- stage: Build
  displayName: Build Agent Images
  jobs:  
  - job: Build
    displayName: Build 
    steps:
       - task: CmdLine@2
         displayName: 'Build and Push Image'
         inputs:
            script: |
              cd agents/init-agents  
              docker build -t agents:$(VER) .          
              docker login $(acrRegistry) --username $(acrusername) --password $(azureACRToken)
              docker tag agents:$(VER) $(acrRegistry)/$(acrRepository):$(VER)
              docker push $(acrRegistry)/$(acrRepository):$(VER)
              docker rmi $(acrRegistry)/$(acrRepository):$(VER)

- stage: Deploy
  displayName: Deploy Agents on AKS cluster
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    condition: succeeded()
    displayName: Deploy Docker Buid Agents Job
    
    steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'Achinta-aks'
              namespace: 'ado-agents'
              command: 'login'
            
          - task: CmdLine@2
            displayName: 'Replace Tokens'
            inputs:
                script: |
                   sed -i 's,AZP_POOL_NAME,$(PoolName),g' agents/deployments/init-agents/init-agents.yaml
                   sed -i 's,AZP_URL_VALUE,$(OrganizationURL),g' agents/deployments/init-agents/init-agents.yaml
                   sed -i 's,AZP_TOKEN_SECRET,$(Pat),g' agents/deployments/init-agents/init-agents.yaml
                   sed -i 's,ACR_NAME,$(acrRegistry),g' agents/deployments/init-agents/init-agents.yaml
                   sed -i 's,VER,$(VER),g' agents/deployments/init-agents/init-agents.yaml
                   sed -i 's,REPOSITORY_NAME,$(acrRepository),g' agents/deployments/init-agents/init-agents.yaml
                   cat agents/deployments/init-agents/init-agents.yaml
          - task: CmdLine@2
            displayName: 'Deploy'
            inputs:
                script: |
                  kubectl apply -f agents/deployments/init-agents/init-agents.yaml -n ado-agents   
              
