apiVersion: v1
kind: Pod
metadata:
    name: #__#BUILD_AGENT_NAME#__# 
spec:
    containers:
    - image: docker:1.12.6-dind
      imagePullPolicy: IfNotPresent
      name: docker-daemon
      resources:
        requests:
          cpu: 20m
          memory: 512Mi
        limits:
          cpu: 2
          memory: 4Gi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /var/lib/docker
        name: docker-graph-storage

    - name: ondemand-agents
      image: #__#ACR_NAME#__#/#__#REPOSITORY_NAME#__#:#__#AGENT_VER#__#
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 2Gi
      env:
      - name: DOCKER_HOST 
        value: "tcp://localhost:2375"
      - name: AZP_POOL
        value: #__#AZP_POOL_NAME#__#
      - name: AZP_TOKEN
        value: #__#AZP_TOKEN_SECRET#__#
      - name: AZP_URL
        value: #__#AZP_URL_VALUE#__# 
      - name: AGENT_TYPE
        value: 'ondemand'   
    imagePullSecrets:
    - name: soham-acr-secret   
    volumes: 
    - name: docker-graph-storage 
      emptyDir: {}








# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ondemand-agent
# spec:
#   replicas: 3
#   progressDeadlineSeconds: 1800
#   selector:
#     matchLabels:
#       app: ondemand-agent
#   template:
#     metadata:
#       labels:
#         app: ondemand-agent
#     spec:
#       containers:
#         - image: docker:1.12.6-dind
#           imagePullPolicy: IfNotPresent
#           name: docker-daemon
#           resources:
#             requests:
#               cpu: 20m
#               memory: 512Mi
#             limits:
#               cpu: 1
#               memory: 2Gi
#           securityContext:
#             privileged: true
#           volumeMounts:
#           - mountPath: /var/lib/docker
#             name: docker-graph-storage

#         - name: ondemand-agents
#           image: ACR_NAME/REPOSITORY_NAME:VER
#           ports:
#           - containerPort: 80
#           resources:
#             requests:
#               cpu: 100m
#               memory: 512Mi
#             limits:
#               cpu: 1
#               memory: 2Gi
#           env:
#             - name: DOCKER_HOST 
#               value: "tcp://localhost:2375"
#             - name: AZP_POOL
#               value: AZP_POOL_NAME
#             - name: AZP_TOKEN
#               value: AZP_TOKEN_SECRET
#             - name: AZP_URL
#               value: AZP_URL_VALUE    
#       imagePullSecrets:
#         - name: soham-acr-secret
#       volumes: 
#       - name: docker-graph-storage 
#         emptyDir: {}





# apiVersion: v1
# kind: Pod
# metadata:
#     name: ondemand-agent
# spec:
#     containers:
#     - image: docker:1.12.6-dind
#       imagePullPolicy: IfNotPresent
#       name: docker-daemon
#       resources:
#         requests:
#           cpu: 20m
#           memory: 512Mi
#         limits:
#           cpu: 1
#           memory: 2Gi
#       securityContext:
#         privileged: true
#       volumeMounts:
#       - mountPath: /var/lib/docker
#         name: docker-graph-storage

#     - name: ondemand-agents
#       image: ACR_NAME/REPOSITORY_NAME:VER
#       ports:
#       - containerPort: 80
#       resources:
#         requests:
#           cpu: 100m
#           memory: 512Mi
#         limits:
#           cpu: 1
#           memory: 2Gi
#       env:
#       - name: DOCKER_HOST 
#         value: "tcp://localhost:2375"
#       - name: AZP_POOL
#         value: AZP_POOL_NAME
#       - name: AZP_TOKEN
#         value: AZP_TOKEN_SECRET
#       - name: AZP_URL
#         value: AZP_URL_VALUE
#       # - name: AGENT_TYPE
#       #   value: 'ondemand'   
#     imagePullSecrets:
#     - name: soham-acr-secret   
#     volumes: 
#     - name: docker-graph-storage 
#       emptyDir: {}
