
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-agents-spin-up
spec:
  replicas: 5
  progressDeadlineSeconds: 1800
  selector:
    matchLabels:
      app: init-agents-spin-up
  template:
    metadata:
      labels:
        app: init-agents-spin-up
    spec:
      containers:
        - name: init-agents-spin-up
          image: ACR_NAME/REPOSITORY_NAME:VER
          # image: NGC_ACR_NAME/NGC_REPOSITORY_NAME:VER
          # image: dcr-camp-dev.pwc.in/initagents:VER
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 0.5
              memory: 1Gi
          env:
            - name: AZP_POOL
              value: AZP_POOL_NAME
            - name: AZP_TOKEN
              value: AZP_TOKEN_SECRET
            - name: AZP_URL
              value: AZP_URL_VALUE
            - name: AGENT_TYPE
              value: 'spin-up'    
      imagePullSecrets:
        - name: soham-acr-secret 
        # - name: reg-cred-secret
      

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-agents-spin-off
spec:
  replicas: 5
  progressDeadlineSeconds: 1800
  selector:
    matchLabels:
      app: init-agents-spin-off
  template:
    metadata:
      labels:
        app: init-agents-spin-off
    spec:
      containers:
        - name: init-agents-spin-off
          image: ACR_NAME/REPOSITORY_NAME:VER
#          image: NGC_ACR_NAME/NGC_REPOSITORY_NAME:VER
          # image: dcr-camp-dev.pwc.in/initagents:VER
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 0.5
              memory: 1Gi
          env:
            - name: AZP_POOL
              value: AZP_POOL_NAME
            - name: AZP_TOKEN
              value: AZP_TOKEN_SECRET
            - name: AZP_URL
              value: AZP_URL_VALUE
            - name: AGENT_TYPE
              value: 'spin-off'    
      imagePullSecrets:
        - name: soham-acr-secret 
        # - name: reg-cred-secret   
      
      

---

apiVersion: v1
kind: Service
metadata:
  name: init-agents-spin-up
spec:
  selector:
    app: init-agents-spin-up
  type: ClusterIP
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: init-agents-spin-off
spec:
  selector:
    app: init-agents-spin-off
  type: ClusterIP
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443